CREATE INDEX IDX_APP_PATIENT ON OPD_APPOINTMENTS(PATIENT_ID);
CREATE INDEX IDX_APP_DATE_DOC ON OPD_APPOINTMENTS(APPOINTMENT_DATE, DOCTOR_ID);



CREATE INDEX IDX_BED_WARD ON ADT_BED_MASTER(WARD_ID);
CREATE INDEX IDX_ADM_PAT ON ADT_ADMISSIONS(PATIENT_ID);
CREATE INDEX IDX_LOG_ADM ON ADT_BED_MOVEMENT_LOG(ADMISSION_ID);



CREATE INDEX IDX_BATCH_EXPIRY ON INV_ITEM_BATCHES(ITEM_ID, EXPIRY_DATE ASC);



CREATE INDEX IDX_BILL_PATIENT ON FIN_BILL_HEADERS(PATIENT_ID);
CREATE INDEX IDX_CLAIM_BILL ON FIN_INSURANCE_CLAIMS(BILL_ID);
