--INSERT SEED DATA
INSERT INTO HMS_LOOKUPS VALUES ('GENDER', 'M', 'Male', 'Male Patient', 'Y');
INSERT INTO HMS_LOOKUPS VALUES ('GENDER', 'F', 'Female', 'Female Patient', 'Y');
INSERT INTO HMS_LOOKUPS VALUES ('GENDER', 'O', 'Other', 'Other', 'Y');
INSERT INTO HMS_LOOKUPS VALUES ('BLOOD_GROUP', 'O+', 'O Positive', 'Universal Donor', 'Y');
INSERT INTO HMS_LOOKUPS VALUES ('BLOOD_GROUP', 'A+', 'A Positive', '', 'Y');
INSERT INTO HMS_LOOKUPS VALUES ('BLOOD_GROUP', 'B+', 'B Positive', '', 'Y');
INSERT INTO HMS_LOOKUPS VALUES ('BLOOD_GROUP', 'AB+', 'AB Positive', '', 'Y');
INSERT INTO HMS_LOOKUPS VALUES ('BLOOD_GROUP', 'O-', 'O Negative', '', 'Y');
INSERT INTO HMS_LOOKUPS VALUES ('BLOOD_GROUP', 'A-', 'A Negative', '', 'Y');
INSERT INTO HMS_LOOKUPS VALUES ('BLOOD_GROUP', 'B-', 'B Negative', '', 'Y');
INSERT INTO HMS_LOOKUPS VALUES ('BLOOD_GROUP', 'AB-', 'AB Negative', '', 'Y');
INSERT INTO HMS_LOOKUPS VALUES ('CITY', 'MUM', 'Mumbai', 'Metro City', 'Y');
INSERT INTO HMS_LOOKUPS VALUES ('CITY', 'PUN', 'Pune', 'IT Hub', 'Y');
INSERT INTO HMS_LOOKUPS VALUES ('CITY', 'DEL', 'Delhi', 'Capital', 'Y');
INSERT INTO HMS_LOOKUPS VALUES ('CITY', 'BLR', 'Bangalore', 'Tech City', 'Y');
COMMIT;


INSERT INTO HMS_DEPARTMENTS (DEPT_NAME, DEPT_CODE) VALUES ('General Medicine', 'GENMED');
INSERT INTO HMS_DEPARTMENTS (DEPT_NAME, DEPT_CODE) VALUES ('Orthopedics', 'ORTHO');
INSERT INTO HMS_DEPARTMENTS (DEPT_NAME, DEPT_CODE) VALUES ('Cardiology', 'CARDIO');
INSERT INTO HMS_DEPARTMENTS (DEPT_NAME, DEPT_CODE) VALUES ('Pediatrics', 'PEDIA');
COMMIT;


