CREATE SEQUENCE SEQ_PATIENT_ID START WITH 1000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_DOCTOR_ID START WITH 500 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_DEPT_ID START WITH 10 INCREMENT BY 10 NOCACHE;



CREATE SEQUENCE SEQ_APPOINTMENT_ID START WITH 100000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_SCHEDULE_ID START WITH 1 INCREMENT BY 1 NOCACHE;



CREATE SEQUENCE SEQ_ADMISSION_ID START WITH 200000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_WARD_ID START WITH 10 INCREMENT BY 10 NOCACHE;
CREATE SEQUENCE SEQ_BED_ID START WITH 1000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_LOG_ID START WITH 500000 INCREMENT BY 1 NOCACHE;



CREATE SEQUENCE SEQ_TRANS_ID START WITH 500000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_BATCH_ID START WITH 10000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_ITEM_ID START WITH 1000 INCREMENT BY 1 NOCACHE;



CREATE SEQUENCE SEQ_BILL_ID START WITH 900000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CLAIM_ID START WITH 1000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_TARIFF_ID START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_DETAIL_ID START WITH 1000000 INCREMENT BY 1 NOCACHE;
