-- LOOKUP MASTER (Configuration Table)
CREATE TABLE HMS_LOOKUPS (
    LOOKUP_TYPE       VARCHAR2(30) NOT NULL,
    LOOKUP_CODE       VARCHAR2(30) NOT NULL,
    MEANING           VARCHAR2(100) NOT NULL,
    DESCRIPTION       VARCHAR2(255),
    IS_ACTIVE         CHAR(1) DEFAULT 'Y' CHECK (IS_ACTIVE IN ('Y', 'N')),
    CONSTRAINT PK_HMS_LOOKUPS PRIMARY KEY (LOOKUP_TYPE, LOOKUP_CODE)
);



--DEPARTMENT MASTER
CREATE TABLE HMS_DEPARTMENTS (
    DEPT_ID           NUMBER(5) primary key,
    DEPT_NAME         VARCHAR2(100) NOT NULL,
    DEPT_CODE         VARCHAR2(10) UNIQUE,
    IS_ACTIVE         CHAR(1) DEFAULT 'Y' CHECK (IS_ACTIVE IN ('Y', 'N'))
);



-- DOCTOR MASTER
CREATE TABLE HMS_DOCTOR_MASTER (
    DOCTOR_ID         NUMBER(10) PRIMARY KEY,
    FULL_NAME         VARCHAR2(100) NOT NULL,
    SPECIALIZATION    VARCHAR2(50),
    DEPT_ID           NUMBER(5) REFERENCES HMS_DEPARTMENTS(DEPT_ID),
    MOBILE_NO         VARCHAR2(15) UNIQUE NOT NULL,
    EMAIL             VARCHAR2(100) CHECK (EMAIL LIKE '%@%'),
    CONSULTATION_FEE  NUMBER(10, 2) DEFAULT 500,
    JOINING_DATE      DATE DEFAULT SYSDATE,
    IS_ACTIVE         CHAR(1) DEFAULT 'Y' CHECK (IS_ACTIVE IN ('Y', 'N')),
    -- Audit Columns
    CREATED_BY        VARCHAR2(50),
    CREATION_DATE     DATE,
    LAST_UPDATED_BY   VARCHAR2(50),
    LAST_UPDATE_DATE  DATE
);



-- PATIENT MASTER
CREATE TABLE HMS_PATIENT_MASTER (
    PATIENT_ID        NUMBER(10) PRIMARY KEY,
    UHID              VARCHAR2(20) UNIQUE NOT NULL,
    FIRST_NAME        VARCHAR2(50) NOT NULL,
    LAST_NAME         VARCHAR2(50) NOT NULL,
    DATE_OF_BIRTH     DATE NOT NULL, 
    GENDER            VARCHAR2(10) NOT NULL CHECK (GENDER IN ('M', 'F', 'O')),
    MOBILE_NO         VARCHAR2(15) NOT NULL,
    EMAIL             VARCHAR2(100) CHECK (EMAIL LIKE '%@%'),
    ADDRESS           VARCHAR2(255),
    CITY              VARCHAR2(50),
    BLOOD_GROUP       VARCHAR2(5),
    -- Audit Columns
    REGISTERED_DATE   DATE DEFAULT SYSDATE,
    CREATED_BY        VARCHAR2(50),
    LAST_UPDATED_BY   VARCHAR2(50),
    LAST_UPDATE_DATE  DATE,
    IS_ACTIVE         CHAR(1) DEFAULT 'Y'
);



--SCHEDULE MASTER (The Rules)
CREATE TABLE OPD_SCHEDULE_MASTER (
    SCHEDULE_ID       NUMBER(10) PRIMARY KEY,
    DOCTOR_ID         NUMBER(10) NOT NULL REFERENCES HMS_DOCTOR_MASTER(DOCTOR_ID),
    DAY_OF_WEEK       VARCHAR2(3) NOT NULL CHECK (DAY_OF_WEEK IN ('MON','TUE','WED','THU','FRI','SAT','SUN')),
    START_TIME        VARCHAR2(5) NOT NULL CHECK (REGEXP_LIKE(START_TIME, '^([0-1][0-9]|2[0-3]):[0-5][0-9]$')), 
    END_TIME          VARCHAR2(5) NOT NULL CHECK (REGEXP_LIKE(END_TIME, '^([0-1][0-9]|2[0-3]):[0-5][0-9]$')),
    AVG_CONSULT_TIME  NUMBER(3) DEFAULT 15,
    IS_ACTIVE         CHAR(1) DEFAULT 'Y' CHECK (IS_ACTIVE IN ('Y', 'N')),
    -- Audit
    CREATED_BY        VARCHAR2(50),
    CREATION_DATE     DATE DEFAULT SYSDATE,
    LAST_UPDATED_BY   VARCHAR2(50),
    LAST_UPDATE_DATE  DATE,
    CONSTRAINT UK_DOC_DAY UNIQUE (DOCTOR_ID, DAY_OF_WEEK)
);


-- APPOINTMENT TRANSACTION (The Booking)
CREATE TABLE OPD_APPOINTMENTS (
    APPOINTMENT_ID    NUMBER(18) PRIMARY KEY,
    APPOINTMENT_NO    VARCHAR2(20) UNIQUE NOT NULL,
    DOCTOR_ID         NUMBER(10) NOT NULL REFERENCES HMS_DOCTOR_MASTER(DOCTOR_ID),
    PATIENT_ID        NUMBER(10) NOT NULL REFERENCES HMS_PATIENT_MASTER(PATIENT_ID),
    APPOINTMENT_DATE  DATE NOT NULL, 
    SLOT_START_TIME   VARCHAR2(5) NOT NULL CHECK (REGEXP_LIKE(SLOT_START_TIME, '^([0-1][0-9]|2[0-3]):[0-5][0-9]$')),
    TOKEN_NUMBER      NUMBER(4) NOT NULL,
    STATUS            VARCHAR2(20) DEFAULT 'BOOKED' CHECK (STATUS IN ('BOOKED', 'CHECKED_IN', 'COMPLETED', 'CANCELLED')),
    CONSULTATION_FEE  NUMBER(10,2), 
    -- Audit
    BOOKED_DATE       DATE DEFAULT SYSDATE,
    CREATED_BY        VARCHAR2(50),
    LAST_UPDATED_BY   VARCHAR2(50),
    LAST_UPDATE_DATE  DATE,
    CONSTRAINT UK_DOC_SLOT UNIQUE (DOCTOR_ID, APPOINTMENT_DATE, SLOT_START_TIME)
);



--WARD MASTER
CREATE TABLE ADT_WARD_MASTER (
    WARD_ID           NUMBER(5) PRIMARY KEY,
    WARD_NAME         VARCHAR2(50) NOT NULL,
    WARD_TYPE         VARCHAR2(20) CHECK (WARD_TYPE IN ('CRITICAL', 'GENERAL', 'PRIVATE')),
    BASE_COST_PER_DAY NUMBER(10,2) NOT NULL,
    IS_ACTIVE         CHAR(1) DEFAULT 'Y'
);



--BED MASTER (The Asset)
CREATE TABLE ADT_BED_MASTER (
    BED_ID            NUMBER(10) PRIMARY KEY, 
    BED_NUMBER        VARCHAR2(10) UNIQUE NOT NULL, 
    WARD_ID           NUMBER(5) NOT NULL REFERENCES ADT_WARD_MASTER(WARD_ID),
    CURRENT_STATUS    VARCHAR2(20) DEFAULT 'VACANT' 
                      CONSTRAINT CHK_BED_STATUS CHECK (CURRENT_STATUS IN ('VACANT', 'OCCUPIED', 'HOUSEKEEPING', 'MAINTENANCE')),
    LAST_UPDATED_BY   VARCHAR2(50),
    LAST_UPDATE_DATE  DATE
);



--ADMISSIONS (The Stay)
CREATE TABLE ADT_ADMISSIONS (
    ADMISSION_ID      NUMBER(18) PRIMARY KEY,
    ADMISSION_NO      VARCHAR2(20) UNIQUE NOT NULL,
    PATIENT_ID        NUMBER(10) NOT NULL REFERENCES HMS_PATIENT_MASTER(PATIENT_ID),
    DOCTOR_ID         NUMBER(10) NOT NULL REFERENCES HMS_DOCTOR_MASTER(DOCTOR_ID),
    ADMISSION_DATE    DATE DEFAULT SYSDATE NOT NULL,
    DISCHARGE_DATE    DATE, 
    ADMISSION_TYPE    VARCHAR2(20) CHECK (ADMISSION_TYPE IN ('EMERGENCY', 'PLANNED')),
    STATUS            VARCHAR2(20) DEFAULT 'ADMITTED' CHECK (STATUS IN ('ADMITTED', 'DISCHARGED')),
    -- Audit
    CREATED_BY        VARCHAR2(50),
    CREATION_DATE     DATE DEFAULT SYSDATE,
    LAST_UPDATE_DATE  DATE
);



--BED MOVEMENT LOG (The Immutable Billing Ledger)
CREATE TABLE ADT_BED_MOVEMENT_LOG (
    LOG_ID            NUMBER(18) PRIMARY KEY, 
    ADMISSION_ID      NUMBER(18) NOT NULL REFERENCES ADT_ADMISSIONS(ADMISSION_ID),
    BED_ID            NUMBER(10) NOT NULL REFERENCES ADT_BED_MASTER(BED_ID),
    CHECK_IN_TIME     DATE NOT NULL,
    CHECK_OUT_TIME    DATE, 
    COST_PER_DAY      NUMBER(10,2), 
    CREATED_BY        VARCHAR2(50)
);



--ITEM MASTER
CREATE TABLE INV_ITEM_MASTER (
    ITEM_ID           NUMBER(10) PRIMARY KEY,
    ITEM_CODE         VARCHAR2(20) UNIQUE NOT NULL, 
    ITEM_NAME         VARCHAR2(100) NOT NULL,
    GENERIC_NAME      VARCHAR2(100),
    UOM               VARCHAR2(10) NOT NULL,
    REORDER_LEVEL     NUMBER(5) DEFAULT 50,
    IS_ACTIVE         CHAR(1) DEFAULT 'Y',
    CREATED_BY        VARCHAR2(50),
    CREATION_DATE     DATE DEFAULT SYSDATE
);



--BATCH INVENTORY
CREATE TABLE INV_ITEM_BATCHES (
    BATCH_ID          NUMBER(10) PRIMARY KEY,
    BATCH_NO          VARCHAR2(50) NOT NULL,
    ITEM_ID           NUMBER(10) NOT NULL REFERENCES INV_ITEM_MASTER(ITEM_ID),
    EXPIRY_DATE       DATE NOT NULL,
    CURRENT_QTY       NUMBER(10) DEFAULT 0 CHECK (CURRENT_QTY >= 0), 
    PURCHASE_RATE     NUMBER(10,2), 
    MRP               NUMBER(10,2), 
    -- Audit
    RECEIVED_DATE     DATE DEFAULT SYSDATE,
    LAST_UPDATED_DATE DATE,
    CONSTRAINT UK_ITEM_BATCH UNIQUE (ITEM_ID, BATCH_NO)
);



--STOCK LEDGER (The Immutable Audit Trail)
CREATE TABLE INV_MATERIAL_TRANSACTIONS (
    TRANS_ID          NUMBER(18) PRIMARY KEY,
    TRANS_DATE        DATE DEFAULT SYSDATE,
    TRANS_TYPE        VARCHAR2(20) CHECK (TRANS_TYPE IN ('GRN', 'ISSUE', 'RETURN')),
    ITEM_ID           NUMBER(10) REFERENCES INV_ITEM_MASTER(ITEM_ID),
    BATCH_ID          NUMBER(10) REFERENCES INV_ITEM_BATCHES(BATCH_ID),
    QTY               NUMBER(10) NOT NULL, 
    SOURCE_REF_ID     NUMBER(18), 
    REMARKS           VARCHAR2(255),
    CREATED_BY        VARCHAR2(50)
);



--BILL HEADER
CREATE TABLE FIN_BILL_HEADERS (
    BILL_ID           NUMBER(18) PRIMARY KEY,
    BILL_NO           VARCHAR2(20) UNIQUE NOT NULL,
    PATIENT_ID        NUMBER(10) NOT NULL REFERENCES HMS_PATIENT_MASTER(PATIENT_ID),
    ADMISSION_ID      NUMBER(18) REFERENCES ADT_ADMISSIONS(ADMISSION_ID), 
    BILL_DATE         DATE DEFAULT SYSDATE NOT NULL,
    TOTAL_AMOUNT      NUMBER(12,2) DEFAULT 0,
    DISCOUNT_AMOUNT   NUMBER(12,2) DEFAULT 0,
    NET_PAYABLE       NUMBER(12,2) DEFAULT 0,
    PAYMENT_STATUS    VARCHAR2(20) DEFAULT 'PENDING' CHECK (PAYMENT_STATUS IN ('PENDING', 'PARTIAL', 'PAID', 'CLAIM_SUBMITTED')),
    -- Audit
    CREATED_BY        VARCHAR2(50),
    CREATION_DATE     DATE DEFAULT SYSDATE
);



--BILL DETAILS (Line Items)
CREATE TABLE FIN_BILL_DETAILS (
    DETAIL_ID         NUMBER(18) PRIMARY KEY, 
    BILL_ID           NUMBER(18) NOT NULL REFERENCES FIN_BILL_HEADERS(BILL_ID),
    SERVICE_TYPE      VARCHAR2(20) CHECK (SERVICE_TYPE IN ('OPD', 'BED_CHARGE', 'PHARMACY', 'PROCEDURE')),
    ITEM_DESCRIPTION  VARCHAR2(200) NOT NULL,
    QTY               NUMBER(10,2) NOT NULL CHECK (QTY > 0),
    UNIT_PRICE        NUMBER(10,2) NOT NULL CHECK (UNIT_PRICE >= 0),
    TOTAL_PRICE       NUMBER(12,2) NOT NULL,
    SOURCE_REF_ID     NUMBER(18) 
);



--INSURANCE CLAIMS (Payer Logic)
CREATE TABLE FIN_INSURANCE_CLAIMS (
    CLAIM_ID          NUMBER(18) PRIMARY KEY,
    CLAIM_NO          VARCHAR2(20) UNIQUE NOT NULL, 
    BILL_ID           NUMBER(18) NOT NULL REFERENCES FIN_BILL_HEADERS(BILL_ID),
    POLICY_NUMBER     VARCHAR2(50),
    CLAIM_STATUS      VARCHAR2(20) DEFAULT 'SUBMITTED' CHECK (CLAIM_STATUS IN ('SUBMITTED', 'APPROVED', 'REJECTED')),
    CLAIMED_AMOUNT    NUMBER(12,2) NOT NULL,
    APPROVED_AMOUNT   NUMBER(12,2) DEFAULT 0,
    DEDUCTION_REASON  VARCHAR2(255),
    -- Audit
    SUBMITTED_DATE    DATE DEFAULT SYSDATE,
    PROCESSED_DATE    DATE
    );
