--Added Trigger to Simulate Identity Column behavior
CREATE OR REPLACE TRIGGER TRG_DEPT_ID
BEFORE INSERT ON HMS_DEPARTMENTS
FOR EACH ROW
BEGIN
    IF :NEW.DEPT_ID IS NULL THEN
        SELECT SEQ_DEPT_ID.NEXTVAL INTO :NEW.DEPT_ID FROM DUAL;
    END IF;
END;



--Trigger to check DATE_OF_BIRTH is not greater that SYSDATE (No future DOBs)
CREATE OR REPLACE TRIGGER trg_check_dob
BEFORE INSERT OR UPDATE ON hms_patient_master
FOR EACH ROW
BEGIN
  IF :NEW.date_of_birth > SYSDATE THEN
    RAISE_APPLICATION_ERROR(-20001, 'Date of birth cannot be in the future');
  END IF;
END;



--AUDIT TRIGGERS
CREATE OR REPLACE TRIGGER TRG_PATIENT_AUDIT
BEFORE INSERT OR UPDATE ON HMS_PATIENT_MASTER
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATED_BY := NVL(SYS_CONTEXT('USERENV', 'OS_USER'), USER);
        :NEW.REGISTERED_DATE := SYSDATE;
    END IF;
    :NEW.LAST_UPDATED_BY := NVL(SYS_CONTEXT('USERENV', 'OS_USER'), USER);
    :NEW.LAST_UPDATE_DATE := SYSDATE;
END;



-- Trigger for Doctor Audit
CREATE OR REPLACE TRIGGER TRG_DOCTOR_AUDIT
BEFORE INSERT OR UPDATE ON HMS_DOCTOR_MASTER
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATED_BY := NVL(SYS_CONTEXT('USERENV', 'OS_USER'), USER);
        :NEW.CREATION_DATE := SYSDATE;
    END IF;
    :NEW.LAST_UPDATED_BY := NVL(SYS_CONTEXT('USERENV', 'OS_USER'), USER);
    :NEW.LAST_UPDATE_DATE := SYSDATE;
END;



-- Trigger to simulate Identity for Schedule ID
CREATE OR REPLACE TRIGGER TRG_SCHED_ID_GEN
BEFORE INSERT ON OPD_SCHEDULE_MASTER
FOR EACH ROW
BEGIN
    IF :NEW.SCHEDULE_ID IS NULL THEN
        SELECT SEQ_SCHEDULE_ID.NEXTVAL INTO :NEW.SCHEDULE_ID FROM DUAL;
    END IF;
END;



--Trigger for Schedule Master Audit
CREATE OR REPLACE TRIGGER TRG_SCHED_AUDIT
BEFORE INSERT OR UPDATE ON OPD_SCHEDULE_MASTER
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATED_BY := NVL(SYS_CONTEXT('USERENV', 'OS_USER'), USER);
        :NEW.CREATION_DATE := SYSDATE;
    END IF;
    :NEW.LAST_UPDATED_BY := NVL(SYS_CONTEXT('USERENV', 'OS_USER'), USER);
    :NEW.LAST_UPDATE_DATE := SYSDATE;
END;



-- Trigger for Appointment Audit
CREATE OR REPLACE TRIGGER TRG_APP_AUDIT
BEFORE INSERT OR UPDATE ON OPD_APPOINTMENTS
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATED_BY := NVL(SYS_CONTEXT('USERENV', 'OS_USER'), USER);
        :NEW.BOOKED_DATE := SYSDATE;
    END IF;
    :NEW.LAST_UPDATED_BY := NVL(SYS_CONTEXT('USERENV', 'OS_USER'), USER);
    :NEW.LAST_UPDATE_DATE := SYSDATE;
END;



--Trigger for Ward ID
CREATE OR REPLACE TRIGGER TRG_WARD_ID_GEN
BEFORE INSERT ON ADT_WARD_MASTER FOR EACH ROW
BEGIN
    IF :NEW.WARD_ID IS NULL THEN
        SELECT SEQ_WARD_ID.NEXTVAL INTO :NEW.WARD_ID FROM DUAL;
    END IF;
END;



--Trigger for Bed ID
CREATE OR REPLACE TRIGGER TRG_BED_ID_GEN
BEFORE INSERT ON ADT_BED_MASTER FOR EACH ROW
BEGIN
    IF :NEW.BED_ID IS NULL THEN
        SELECT SEQ_BED_ID.NEXTVAL INTO :NEW.BED_ID FROM DUAL;
    END IF;
END;



--Trigger for Log ID
CREATE OR REPLACE TRIGGER TRG_LOG_ID_GEN
BEFORE INSERT ON ADT_BED_MOVEMENT_LOG FOR EACH ROW
BEGIN
    IF :NEW.LOG_ID IS NULL THEN
        SELECT SEQ_LOG_ID.NEXTVAL INTO :NEW.LOG_ID FROM DUAL;
    END IF;
END;



--AUDIT TRIGGERS
CREATE OR REPLACE TRIGGER TRG_ADM_AUDIT
BEFORE INSERT OR UPDATE ON ADT_ADMISSIONS
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATED_BY := NVL(SYS_CONTEXT('USERENV', 'OS_USER'), USER);
        :NEW.CREATION_DATE := SYSDATE;
    END IF;
    :NEW.LAST_UPDATE_DATE := SYSDATE;
END;


CREATE OR REPLACE TRIGGER TRG_BED_AUDIT
BEFORE UPDATE ON ADT_BED_MASTER
FOR EACH ROW
BEGIN
    :NEW.LAST_UPDATED_BY := NVL(SYS_CONTEXT('USERENV', 'OS_USER'), USER);
    :NEW.LAST_UPDATE_DATE := SYSDATE;
END;



--Trigger for Item ID
CREATE OR REPLACE TRIGGER TRG_ITEM_ID
BEFORE INSERT ON INV_ITEM_MASTER FOR EACH ROW
BEGIN
    IF :NEW.ITEM_ID IS NULL THEN
        SELECT SEQ_ITEM_ID.NEXTVAL INTO :NEW.ITEM_ID FROM DUAL;
    END IF;
END;



--AUDIT TRIGGERS
CREATE OR REPLACE TRIGGER TRG_BATCH_AUDIT
BEFORE UPDATE ON INV_ITEM_BATCHES
FOR EACH ROW
BEGIN
    :NEW.LAST_UPDATED_DATE := SYSDATE;
END;



--TARIFF MASTER
CREATE TABLE FIN_TARIFF_MASTER (
    SERVICE_ID        NUMBER(10) PRIMARY KEY, 
    SERVICE_CODE      VARCHAR2(20) UNIQUE NOT NULL,
    SERVICE_NAME      VARCHAR2(100) NOT NULL,
    CHARGE_AMOUNT     NUMBER(10,2) NOT NULL CHECK (CHARGE_AMOUNT >= 0),
    EFFECTIVE_FROM    DATE DEFAULT SYSDATE,
    EFFECTIVE_TO      DATE,
    IS_ACTIVE         CHAR(1) DEFAULT 'Y'
);



--Trigger for Tariff ID
CREATE OR REPLACE TRIGGER TRG_TARIFF_ID
BEFORE INSERT ON FIN_TARIFF_MASTER FOR EACH ROW
BEGIN
    IF :NEW.SERVICE_ID IS NULL THEN
        SELECT SEQ_TARIFF_ID.NEXTVAL INTO :NEW.SERVICE_ID FROM DUAL;
    END IF;
END;



--Trigger for Bill Detail ID
CREATE OR REPLACE TRIGGER TRG_DETAIL_ID
BEFORE INSERT ON FIN_BILL_DETAILS FOR EACH ROW
BEGIN
    IF :NEW.DETAIL_ID IS NULL THEN
        SELECT SEQ_DETAIL_ID.NEXTVAL INTO :NEW.DETAIL_ID FROM DUAL;
    END IF;
END;



--AUDIT TRIGGERS
CREATE OR REPLACE TRIGGER TRG_BILL_AUDIT
  BEFORE INSERT ON FIN_BILL_HEADERS
  FOR EACH ROW
BEGIN
  :NEW.CREATED_BY    := NVL(SYS_CONTEXT('USERENV', 'OS_USER'), USER);
  :NEW.CREATION_DATE := SYSDATE;
END;
